- name: Setting the required folder structure
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
  with_items:
  - /data/services/logs
  - /data/services/contracts
  - /data/services/configurations/
  - /data/services/generated-properties

- name: Creating symlink in contracts directory
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: vagrant
    group: vagrant
  with_items:
  - {src: /home/vagrant/promotion_planning_service/contracts/contract_files, dest: /data/services/contracts/promotion_planning_service}
  - {src: /home/vagrant/promotion_service/contracts/contract_files, dest: /data/services/contracts/promotion_service}

- name: Creating symlink in config directory
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: vagrant
    group: vagrant
  with_items:
  - {src: /home/vagrant/infrastructure/configuration/log4j.properties, dest: /data/services/configurations/log4j.properties}

- name: Creating symlink in generated properties directory
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: vagrant
    group: vagrant
  with_items:
  - {src: /home/vagrant/generated_properties/generated-properties/development, dest: /data/services/generated-properties/development}
  - {src: /home/vagrant/generated_properties/generated-properties/test, dest: /data/services/generated-properties/test}
  - {src: /home/vagrant/generated_properties/generated-properties/local, dest: /data/services/generated-properties/local}
  - {src: /home/vagrant/generated_properties/generated-properties/merch-e2e, dest: /data/services/generated-properties/merch-e2e}
  - {src: /home/vagrant/generated_properties/generated-properties/promo-e2e, dest: /data/services/generated-properties/promo-e2e}

- name: Creating password file for build_scripts
  become: yes
  copy:
    dest: /home/vagrant/.pgpass
    owner: vagrant
    group: vagrant
    mode: 0600
    content: "localhost:*:*:developer:password"

