- name: Add node repository
  become: yes
  yum_repository:
    name: nodeRepo
    description: nodeRepo
    baseurl: https://rpm.nodesource.com/pub_6.x/el/6/x86_64/
    gpgcheck: no

- name: Install node
  become: yes
  yum:
    name: nodejs-{{node_version}}
    state: present
