- name: Download jdk rpm package
  become: yes
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
    dest: /opt/jdk.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    checksum: sha256:d6808a4a7b96b72e8fbee28a223f94e43a07e970e757b87fc409644716ed7aa0

- name: Installing Oracle-jdk 8
  become: yes
  yum: name=/opt/jdk.rpm